# Generated by Django 5.1.6 on 2025-04-22 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='numbers_of_product_reservate',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
