# Generated by Django 5.1.6 on 2025-05-14 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_alter_tag_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TagCategory',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='category',
        ),
    ]
