# Generated by Django 5.1.6 on 2025-05-14 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_alter_category_name_alter_tag_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='tags',
        ),
    ]
