# Generated by Django 5.1.6 on 2025-05-14 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_product_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='category',
        ),
        migrations.DeleteModel(
            name='CategoryTag',
        ),
    ]
