# Generated by Django 5.1.6 on 2025-05-19 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_remove_tag_category_delete_categorytag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='calories',
        ),
        migrations.RemoveField(
            model_name='product',
            name='numbers_of_product',
        ),
        migrations.RemoveField(
            model_name='product',
            name='numbers_of_product_reservate',
        ),
        migrations.RemoveField(
            model_name='product',
            name='units',
        ),
    ]
