# Generated by Django 5.1.6 on 2025-03-10 10:12

import json.encoder
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_customuser_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=models.JSONField(encoder=json.encoder.JSONEncoder.encode),
        ),
    ]
