# Generated by Django 5.1.6 on 2025-04-22 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_product_numbers_of_product_reservate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, default='../media/image/strawberry.png', upload_to='../media/image'),
        ),
    ]
