# Generated by Django 5.1.6 on 2025-04-22 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, default='image/strawberry.png', upload_to='image'),
        ),
    ]
