# Generated by Django 5.1.6 on 2025-05-20 11:01

import django.db.models.deletion
from django.db import migrations, models

# def create_statuses(apps, schema_editor):
#     Status = apps.get_model('order', 'Status')
#     Status.objects.create(name='Formed')
#     Status.objects.create(name='In process')
#     Status.objects.create(name='Completed')


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_shopfilial_lat_shopfilial_lon'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='order',
            name='is_paid',
        ),
        migrations.AddField(
            model_name='order',
            name='order_status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='status', to='order.status'),
        ),
        # migrations.RunPython(create_statuses),
    
    ]
