
services:
  web:
    build: .
    ports:
      - 8000:8000  

    environment:
      CELERY_BROKER_URL: "redis://redis:6379/0"
      CELERY_RESULT_BACKEND: "redis://redis:6379/0"
      DJANGO_DB: postgresql
      POSTGRES_HOST: db
      POSTGRES_NAME: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_PORT: 5432
    command: bash -c "python manage.py makemigrations &&
                     python manage.py migrate &&
                     python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./ponchykBoy:/ponchykBoy
    depends_on:
      - db
      - redis

  db:
    image: postgres:16.8-alpine3.20

    volumes:
      - ./ponchykBoy:/ponchykBoy
   
    environment:
      DJANGO_DB: postgresql
      POSTGRES_HOST: db
      POSTGRES_NAME: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_PORT: 5432
    expose:
     - 5432:5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    

  redis:
    image: redis:7.4-alpine
    hostname: redis
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel debug

  worker:
    build: .
    hostname: celery
    restart: always
    volumes:
      - ./ponchykBoy:/ponchykBoy

    command: celery -A backend.celery_conf worker --loglevel=INFO

    environment:
      CELERY_BROKER_URL: "redis://redis:6379/0"
      CELERY_RESULT_BACKEND: "redis://redis:6379/0"

    depends_on:
      - redis
      - web

  react:
    build: ./frontend
    restart: always
    ports:
      - "5173:5173"
    environment:
       - CHOKIDAR_USEPOLLING=true
    volumes:
      - ./frontend/my-app:/frontend/my-app
      - /frontend/my-app/node_modules/
    depends_on:
      - web

  flower:
    build: .
    hostname: flower
    restart: always
    command: celery -A backend.celery_conf flower
    volumes:
      - ./ponchykBoy:/ponchykBoy
    ports:
      - "5555:5555"
    links:
      - redis
    environment:
      CELERY_BROKER_URL: "redis://redis:6379/0"
      CELERY_RESULT_BACKEND: "redis://redis:6379/0"
    depends_on:
      - web
      - redis
      - worker
